### ISSUE TITLE
Can't place command blocks as builder/Prison Mobs

### ISSUE THREAD

**Issue by thepenmen22** [artfcl-intlgnce/XXMC#101]
Building prison and was thinking about traps that could use arrow spawners and custom zombies/wolves as guards/guard dog. But realized I couldn't place them in the world. Fated tried it, but idk if he couldn't either or just didn't want to risk it with me messing with command blocks.

Are they not enabled or do I just not have permission to place them? Should I instead test out the commands in single player and let let you guys place them in the prison area?

If custom spawners using command blocks aren't possible or are too risky, we could use just zombies and other mobs. Would not be able to use wolves because spawner would allow them to spawn aggressive.

**Comment by FatedKusari** [comment]
Commandblocks are usable by OP's only. This is to prevent anyone who has access to them from giving themself "powers" they shouldn't have.

**Comment by thepenmen22** [comment]
Tbh I could probably already do a lot of damages with all the permissions I have :P But yeah I get what you mean, it's always a risk to allow people that sort of power.

So what is the conclusion based on the post suggestions then? Or is that something art decides?

**Comment by artfcl-intlgnce** [comment]
Command Blocks are not enabled, even OPs cant get command blocks to execute unfortunately. 
We have MythicMobs though, so @FatedKusari could help you get custom mobs figured out. He's the lead on mobs and NPCs

**Comment by FatedKusari** [comment]
Mobs are a bit easier, I can set up "Guard" mobs.

Give me some details and we can work something out:

Mob Type:
Skin:
Mob Name:
Weapon:
Armor:

A few things to work out. But totally doable.

**Comment by thepenmen22** [comment]
Ok I think only 3 different types of mobs are needed. Here is a basic outline of what they could be. Things can be changed around a bit if things don't work or they don't feel/look right.

Mob Type: Zombie
Skin: Some sort of guard skin. Should I try to find a skin, or are there presets you already have?
Mob Name: Prison Guard
Weapon: Sharpness I diamond sword.
Armor: Leather hat, top, and bottom. Iron boots.

Mob Type: Aggressive Wolf (so players don't need to attack one for it to fight them).
Skin: Same as above, some sort of police dog skin.
Mob Name: Guard Dog
Weapon: N/A
Armor: N/A

Mob Type: Skeleton
Skin: Same as above, but slightly different to show this one is a guard with a gun/bow.
Mob Name: Guard Sniper
Weapon: Flame I bow.
Armor: No hat or top. Leather legs, iron boots.

**Comment by FatedKusari** [comment]
I believe this is now done. Another successful case.
