### ISSUE TITLE
Create TrialBuilder Role & add Llama

### ISSUE THREAD

**Issue by thepenmen22** [artfcl-intlgnce/XXMC#102]
He's supposed to be working on his track, but has to wait for someone to give him creative each time he gets on, which is fine since he's in trial still. But the problem is that his track is supposed to go in a very specific place at spawn and needs to be build in a specific way, and he can't edit spawn.

Idk how to give him permission to do that, art does. When art gave it to him, llama had to log for a bit and when he came back the perm was gone. His time isn't lining up with art's and so he is unable to work on his  build to become a server builder.

**Comment by artfcl-intlgnce** [comment]
Changed my mind. Ppl doing trial build cannot have creative unsupervised. If they routintely go AFK during a build test just Fail them.

**Comment by artfcl-intlgnce** [comment]
@thepenmen22 Now that you are senior builder you will have the perms required to handle those situations. (you can give creative)
