### ISSUE TITLE
Elytra flying bugged. When picking up speed, it pulls you back.

### ISSUE THREAD

**Issue by thepenmen22** [artfcl-intlgnce/XXMC#103]
This is a problem for parkour maps (mainly Lumbridge) since some obstacles require an elytra to go fast onto a distant block. While flying, if a player gets to a certain speed, they get pulled back and their speed is reset.

This makes certain maps undo-able. It also makes it so that if anyone gets an elytra from the end, they will not be able to fly with it.

I tried it during parkour in the Lumbridge map, and others have too. Same problem with all players. Did not matter how many players were on (happened with 2 online, and 8). Tried it at spawn by spawning in an elytra, same thing happened.

I don't really know what the problem could be, but a possibility is some anti-cheat measure that makes players who fly too fast unable to do so.

**Comment by FatedKusari** [comment]
Sounds like bounceback from the Anti-Cheat. 

Shall need to call in those with the stuff in front of them.

**Comment by artfcl-intlgnce** [comment]
Yea sounds like its an Anti-Cheat blocking this. Needs to be tested with an OP who can see the anti-cheat notifications (Im not 100% that Trial Admins have full anticheat notifications)

**Comment by FatedKusari** [comment]
No, everything i see is from experiance. Only notifictions i see are when console kicks for it.

**Comment by artfcl-intlgnce** [comment]
Just changed anticheats, lets test this again in a controlled environment

**Comment by artfcl-intlgnce** [comment]
@thepenmen22 have you tested this since the AntiCheat updates?

**Comment by thepenmen22** [comment]
Sorry haven't been on github in a while, but a few days after this was posted, the bug was fixed. I could finish the parkour perfectly fine. I can't test it again right now because /cp won't work.
