### ISSUE TITLE
Ability to Sell Brews

### ISSUE THREAD

**Issue by artfcl-intlgnce** [artfcl-intlgnce/XXMC#106]
NPC's should also purchase alcohol.

Bartenders should sell alcohol

JazzyTNT offered pricing in discord, she is very familiar with plugin

**Comment by artfcl-intlgnce** [comment]
Same NPC's or do we have different NPC's for alcohol? 

If the same, add to the ones in the data center (/home:artfcl_intlgnce:datacenter). Those are the anchor NPC's which will be copied out to others.

**Comment by artfcl-intlgnce** [comment]
PS only perms you would need are citizens and dtlTraders

**Comment by artfcl-intlgnce** [comment]
Beer 2000. Mead 2050. Apple Mead 2075. Vodka 3500. Rum 4000. Abstinthe 5000.

**Comment by FatedKusari** [comment]
NPC's cannot store the brews.

Stuck on the back burner until ideas flow in.

**Comment by artfcl-intlgnce** [comment]
Players Bomb and Malt are now all in building breweries and are looking for a way to sell their alc. 
I think for the time being Admins can be the alcohol buyers or something until we can find a method to sell the brews (might require getting in touch with their dev). @Scarsz theres a great plugin Brewery that makes custom brews, but we're having troubles finding a way that players can sell their custom brews to the server to get money (the same method they sell drugs)
Maybe a different plugin would work, but dtlTraders doesnt.  (which is what we use for drug buyers)

**Comment by k-lj** [comment]
Cant we use DLTtrader?

**Comment by k-lj** [comment]
because they work for npc guns dont they?

**Comment by artfcl-intlgnce** [comment]
Crimed u gotta read bro .. wastes everyone's time

"Maybe a different plugin would work, but dtlTraders doesnt."

**Comment by artfcl-intlgnce** [comment]
QUICKSHOP has been setup in the Disco to sell brews via chests. 
This is the MVP of this ticket so I am closing. 
Expansion of more Brews as Drugs is tracked at #136
