### ISSUE TITLE
Players Spawning in Old Spawn 

### ISSUE THREAD

**Issue by artfcl-intlgnce** [artfcl-intlgnce/XXMC#109]
Need script to check on player login if they are in world ParadiseFalls. If so, to TP them either to spawn OR to the same coordinates they are at, but in the Christmas world.

**Comment by FatedKusari** [comment]
File sent on DIscord. It is send players to new spawn if they are in old world.

**UPDATE** -- Created an OP bypass to this, moan at me to get the new file.
