### ISSUE TITLE
4th link in /vote doesn't lead directly to vote page

### ISSUE THREAD

**Issue by thepenmen22** [artfcl-intlgnce/XXMC#110]
When doing /vote, the 4th link is to this page:
http://minecraft-mp.com/server-s137914
instead of:
http://minecraft-mp.com/server/137914/vote/

It's not a big problem, but it was fixed for the other websites a while ago. Now it's inconsistent to have 3 leading to vote page while 1 not.

Also on narcowars.net where the vote links are on the right side, planetminecraft is still listed even though it doesn't work anymore. Might be worth submitting server again as just a factions server, or just removing the link all together.

**Comment by FatedKusari** [comment]
**Link has been fixed.**
