### ISSUE TITLE
Use Vouchers in Crates to Avoid Forgery

### ISSUE THREAD

**Issue by artfcl-intlgnce** [artfcl-intlgnce/XXMC#117]
Got this cheap plugin that does vouchers which are perm based, can have redeemable commands (I set them up to mail myself and 2 admins for items like prebuilt bases and spawn statue which requires manual admin work
https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BAvouchers%E2%97%84%E2%97%84-give-your-players-vouchers-in-crates-prizes-and-for-just-being-good.13654/

**Comment by k-lj** [comment]
Aight
Give me full perms to it, and also send crate config

**Comment by k-lj** [comment]
Okay this is finished then, because we already have everything converted. and we dont need them for points, nor kits
