### ISSUE TITLE
Mythic Mobs Not Spawning 

### ISSUE THREAD

**Issue by artfcl-intlgnce** [artfcl-intlgnce/XXMC#119]
Snowmen and Prison Guards are not spawning automatically
Even tried manual spawn of the Guard but it didnt work (manual spawn of snowman does work).
I adjusted the worldguard flags and made prison higher priority, doesn't seem to have worked.

**Comment by FatedKusari** [comment]
regions for spawn and prison were changed. Preventing the mobs used as a base from spawning.

I do ask that if any region changes are made that could impact mobs, do let me know.

**Comment by artfcl-intlgnce** [comment]
Snowmen still not spawning

**Comment by artfcl-intlgnce** [comment]
Plus hostile mobs are all around spawn, can we fix the regions so the mobs only spawn in prison? just make prison region higher priority

**Comment by FatedKusari** [comment]
Mobs will now only spawn in prison area. Regions are not my strongest suit at times. Oh well, we had joy for a short time.
