### ISSUE TITLE
Configure Playershops embedded in Spawn

### ISSUE THREAD

**Issue by artfcl-intlgnce** [artfcl-intlgnce/XXMC#129]
Moving from their own TP to the skatepark area at spawn. 
Copy already done, need build team to work on landscaping (Lutowski) and admin team to work on the region configurations.

**Comment by k-lj** [comment]
Okay ill start on it! might not get it all done tonight but ill get most done <3 also ill get the particles that are running thru them fixed!

**Comment by k-lj** [comment]
Finished, just needs to be tested!

**Comment by k-lj** [comment]
Minor error with the regions, you cant build, break or open chests. something that has to do  with flags or region priority
