### ISSUE TITLE
Suggestions For Secondary Activities?

### ISSUE THREAD

**Issue by k-lj** [artfcl-intlgnce/XXMC#135]
Down below comment the activites we should add
i already have some ideas:
- Casino (Coin Flip, Slots, ETC.)
- Racing (Horses or Cars)
- Paintball Arena
*This is not a main priority*

**Comment by artfcl-intlgnce** [comment]
Casino approved - thought you were working on that? 
For Racing - lets think of whether to do that on factions or a minigame in itself
