### ISSUE TITLE
Crackshot Bug

### ISSUE THREAD

**Issue by artfcl-intlgnce** [artfcl-intlgnce/XXMC#141]
[CrackShot] The weapon 'Carbine' has no value provided for Item_Type!
28.01 23:44:59 [Server] INFO [CrackShot] The weapon 'Tactical_Knife' has no value provided for Item_Type!
28.01 23:44:59 [Server] INFO [CrackShot] The weapon 'Python' has no value provided for Item_Type!

**Comment by k-lj** [comment]
Ill in a bit. that's strange though, considering those weapons are not in the configuration.

**Comment by k-lj** [comment]
Double checked the configuration, nothing wrong with the config.
