### ISSUE TITLE
Bugs/Suggestions

### ISSUE THREAD

**Issue by Wylith** [artfcl-intlgnce/XXMC#23]
Current Rank: Hustler
Commands:
[x] /druglist (no permission)
[x] /tutorial (says unknown command)
[x] /trade (insufficient permission)(certain rank to use) -- Added trader.trade perm to Supplier rank
[x] /parkour (unknown command)
[x] /dailylotto (unknown command)(/dailybonus)
[x] /copranks (insufficient permissions)
[x] /randomtp (only certain areas) ::: Comment: Working as Designed (AI) -- only works in Wilderness. We need to add better instruction to users about this, possibly in /warp tutorial signs -- working as designed for now

**Comment by Wylith** [comment]
Back right of prison has opening in wall.
![screenshot 345](https://cloud.githubusercontent.com/assets/22691538/19207375/5f27c396-8cbe-11e6-9dac-3e8ff5278c96.png)
Back left of prison has opening in wall.
Might want to have some kind of wall around stone platform near prison make it enclosed.
Have some decoration make it look more like a prison than a big empty space.
Might want to change armrests in coffee house, currently have null on side.
Change Shop sign from diamond and gold blocks to painting that has Shop on it, Makes it look more professional. Lots of smaller/newer servers use gold and diamond blocks, other options to make it look better.
Bones/Skeletons should be super rare, you can use bones to make bonemeal and grow drugs quickly for super cheap.

**Comment by Wylith** [comment]
Part of a house isn't finished, leads to part of the wilderness.
![screenshot 347](https://cloud.githubusercontent.com/assets/22691538/19207612/6b834d02-8cc0-11e6-92f9-43e5a177d2b3.png)
Donor Dealer, doesn't work, might be because I am not a donor.
Bar tenders would be cool in coffee shop. Or baristas, have special drinks(potions) give effects, or colored vision just to look cool for player.
Doors do not work in the hotels, apartments, coffee shop.

**Comment by Wylith** [comment]
/kit cook (cook rank does not receive /kit cook)
Ranked up to chemist and kept cook title.

**Comment by artfcl-intlgnce** [comment]
Please create a "New Issue" for each new topic, there is no way to track what is complete and what is not complete on this item.  I fixed the prison and the /Cook rankup. The image you showed is a rear patio with a dor to that building.  I will open each in individual tickets open for 1. Barista enhancement, 2.Donor Dealers 3. Doors not working, 4. armrests 5. prison fences 6. shop sign (low priority) 7. Enhance Prison

**Comment by Wylith** [comment]
So do you want each individual bug in a new issue or have categories for
them?
