### ISSUE TITLE
Friskstick Reporting

### ISSUE THREAD

**Issue by Wylith** [artfcl-intlgnce/XXMC#32]
Normal player is able to report themselves(rank is supplier), after /report playername says report successful and then says internal error.
![screenshot 349](https://cloud.githubusercontent.com/assets/22691538/19215113/08538a8c-8d63-11e6-9917-1258bc09c9ab.png)

**Comment by artfcl-intlgnce** [comment]
Confirmed that this is still submitting reports to the cops, and cops can still view them (/showreports), I will have the dev team review the logs to understand the error. Its likely the deprecation of getPlayerStatus from the Bukkit API, lots of plugs depend on that. But, this is working as designed and not harmful in any way. Thank you for submitting, we will try to get that fixed aesthetically.

**Comment by mat290** [comment]
You can mark this as one of my to-dos.

**Comment by artfcl-intlgnce** [comment]
Report is now not being used by Friskstick, overridden by Tiger Reports used for our Admin playerbehavior /report
