### ISSUE TITLE
Ranks command

### ISSUE THREAD

**Issue by Wylith** [artfcl-intlgnce/XXMC#33]
/ranks has A B C ranks instead of hustler etc.

![screenshot 350](https://cloud.githubusercontent.com/assets/22691538/19215141/e1e2a832-8d63-11e6-842b-e9c290832ba8.png)

**Comment by artfcl-intlgnce** [comment]
Fixed by setting custom EZRanks /ranks to false - now uses EZRanks LADDER no custom message
