### ISSUE TITLE
/trade

### ISSUE THREAD

**Issue by Wylith** [artfcl-intlgnce/XXMC#34]
/trade command  does not work, insufficient permissions

**Comment by artfcl-intlgnce** [comment]
This may be the DTLTraders plugin (the NPC shops) competing with the Trader plugin (/trade). Still investigating

**Comment by artfcl-intlgnce** [comment]
Identified incorrect permission -- trader --> trading*. Ready for retest

**Comment by artfcl-intlgnce** [comment]
tested with my alt - works
