### ISSUE TITLE
Ranks seem to be messed up

### ISSUE THREAD

**Issue by Wylith** [artfcl-intlgnce/XXMC#38]
![screenshot 356](https://cloud.githubusercontent.com/assets/22691538/19215273/33048f3e-8d67-11e6-8aa3-fe00c134a093.png)
 Currently Heisenberg rank, next rank-up is supposed to be Empire, says Chemist when I do /rankup

And name does not change

**Comment by artfcl-intlgnce** [comment]
I don't expect anyone to get to Prestige for several months, so this is being prioritized lower than some of the Showstopper defects. Setting for release 1.3 (october 30)

**Comment by mat290** [comment]
If you want to task this as one of my to-dos.

**Comment by artfcl-intlgnce** [comment]
@mat290 somehow a player is already at Heisenberg so this has come towards top of pile. Ask me on Discord for the EZRanks plugin config when u get a chance

**Comment by artfcl-intlgnce** [comment]
TNTReflexx got there okay, so closing this as we are unable to reproduce
