### ISSUE TITLE
Exits at spawn some are unable to let players out into the wild

### ISSUE THREAD

**Issue by Wylith** [artfcl-intlgnce/XXMC#39]
![screenshot 357](https://cloud.githubusercontent.com/assets/22691538/19215338/46eb3bb8-8d69-11e6-9b12-8c400b1ac4a6.png)

**Comment by artfcl-intlgnce** [comment]
made each exit escapable, but still not pretty. need build team but no longer requirement for initial launch. note: it is intentional to not allow players to run back into the spawn building. build team will need to convey that somehow, potentially glass before the dropdown
