### ISSUE TITLE
Suggested Enhancement: Add mob health bar

### ISSUE THREAD

**Issue by Wylith** [artfcl-intlgnce/XXMC#40]
Mob health bar/health number. e.g. 7.4/10 or (//////  )

**Comment by Wylith** [comment]
Somehow change to factions plugin to be Cartel or Mafia something drug related instead of faction.

**Comment by artfcl-intlgnce** [comment]
factions is the core, drugs is the economy spin. faction power growth is relative to drug farm claim growth. we nee factions, but will investigate others. factions opens us to broader target audience, and staff has more familiarity with it. Will investigate any lightweight alternatives that fulfill power based land claims.
