### ISSUE TITLE
Kit Timers

### ISSUE THREAD

**Issue by Wylith** [artfcl-intlgnce/XXMC#46]
Hustler kit currently has a timer around 30 minutes.
Dealer kit currently has a timer at 1 hour and 40 minutes.
Supplier kit currently has a timer at 1 hour and 40 minutes.
Dispensary kit currently has a timer at 1 hour and 40 minutes.
Grower kit currently has a timer at 1 hour and 40 minutes.
Cook kit currently has a timer at 1 hour and 40 minutes.
Chemist kit currently has a timer at 1 hour and 40 minutes.
Lieutenant kit currently has a timer at 1 hour and 40 minutes.
Jesse Pinkman kit currently has a timer at 1 hour and 40 minutes.
Cartel Kingpin kit currently has a timer at 1 hour and 40 minutes.
Heisenberg kit currently has a timer at 1 hour and 40 minutes.(Does not have access to /craft)

**Comment by artfcl-intlgnce** [comment]
FIxed - ready for restest

**Comment by artfcl-intlgnce** [comment]
King confirmed resolved. Closing
