### ISSUE TITLE
Error when you type /wild

### ISSUE THREAD

**Issue by mat290** [artfcl-intlgnce/XXMC#48]
When you type /wild you get a config error. This might be as easy as hiding the command or not allowing Permissions to it.

https://gyazo.com/c70a0a3340b7a22c06e161dd7e565065

**Comment by artfcl-intlgnce** [comment]
This only works in the wilderness, adding error in spawn to backlog

**Comment by artfcl-intlgnce** [comment]
Worldguard flag to block command
