### ISSUE TITLE
Clean up the Website

### ISSUE THREAD

**Issue by Wylith** [artfcl-intlgnce/XXMC#52]
[ x ] Builders to update landscape, make wild spawn exits a little nicer, and to clean up the city.
[ x ] Finish bug testing Cop ranks and building.
[ x ] Make an update forum post.
Tidy up the website.
[ x ] Recruit a few more active beta testers.

**Comment by artfcl-intlgnce** [comment]
@Kingstell any website update recommendations you have for this? otherwise we will close out the ticket as the other items are complete

**Comment by Wylith** [comment]
Removing the gallery or putting pictures up. Having set threads in forums.
