### ISSUE TITLE
Discuss /duty

### ISSUE THREAD

**Issue by mat290** [artfcl-intlgnce/XXMC#58]
Currently /duty does not give any weapons and because it switches inventories it does not allow you to use weapons from your own inventory.

We need to figure out what we want to do. We could set up a armory inside the Police Station. We can give some weapons with /duty or we can allow gun stores to sell guns for cheap to police.

**Comment by artfcl-intlgnce** [comment]
Related to #72

**Comment by artfcl-intlgnce** [comment]
Merge with #56
