### ISSUE TITLE
FriskStick not confiscating Potatoes or Carrots

### ISSUE THREAD

**Issue by artfcl-intlgnce** [artfcl-intlgnce/XXMC#64]

**Comment by artfcl-intlgnce** [comment]
@Scarsz  Can you look at the source of this and see why all drugs except potatoes and carrots work?
We've tried different block names and ids including. 
potato
potatoes
carrot
carrots

**Comment by Scarsz** [comment]
`"potato" != "potato_item"`
`"carrot" != "carrot_item"`
