### ISSUE TITLE
Diggers

### ISSUE THREAD

**Issue by JoeS8** [artfcl-intlgnce/XXMC#69]
Some new vehicles to complement the new plugin. Diggers would be useful for farm building.

**Comment by artfcl-intlgnce** [comment]
Requesting this from the Vehicles developer - thank you for this suggestion its spot on perfect enhancement in my opinion

**Comment by FatedKusari** [comment]
**What is the chance/timeframe of this one?**

**Comment by artfcl-intlgnce** [comment]
Dev said he's interested in adding, but was adding Jeeps first I believe
