### ISSUE TITLE
In Game Purchasable Kits

### ISSUE THREAD

**Issue by DuddGaming** [artfcl-intlgnce/XXMC#79]
You should implement the ability to purchase kits with in game money

**Comment by JoeS8** [comment]
I like this. Even if we get various levels of armor and tools in the servershop it would be a welcome addition.

**Comment by k-lj** [comment]
I don't know if this is related. but i added them to the shop
http://narcowars.net/shop#kits-1190304

**Comment by artfcl-intlgnce** [comment]
@CrimedTK are they all really worth 2.50?
