### ISSUE TITLE
Create Backup Lobby for Outage

### ISSUE THREAD

**Issue by artfcl-intlgnce** [artfcl-intlgnce/XXMC#84]

**Comment by artfcl-intlgnce** [comment]
Scarsz is assigned from a Bungee/infrastructure perspective, Crimed, you can work with OTBlock on the Design of the "Server Restart" lobby

**Comment by k-lj** [comment]
Okay ill just make it on a new multiverse world called Lobby!

**Comment by artfcl-intlgnce** [comment]
ok, just know that eventually will need to move to a fully different server, not another world within the same server

**Comment by k-lj** [comment]
Yes I know i will copy the cords. and you will move it into the other bungee server (im using the end world for it)

**Comment by k-lj** [comment]
Finsihed (will touch up upon request) pictures of the lobby are at #builds chat channel in discord

**Comment by k-lj** [comment]
Awaiting on Scarsz to finish the bungee cord then we can finalize this task

**Comment by k-lj** [comment]
Finished do /server outage!
