### ISSUE TITLE
Build LeaderHeads Showcase Room

### ISSUE THREAD

**Issue by artfcl-intlgnce** [artfcl-intlgnce/XXMC#89]
Need to build a big /warp leaders, where we can show the top 3-5 players for given stats (mcmmo and others listed below)

Assigned OTBlock57 as Builder. Fated will be the Admin on this.

Leaderheads Plugin: https://www.spigotmc.org/resources/leaderheads.2079/
List of potential statistics (if we have the plugins for them): https://robindebaets.be/leaderheads/variables

**Comment by FatedKusari** [comment]
Thinking of maybe adding the following:

**MCMMO**
Alchemy - Top Chemists
Herbalism - Top Growers

**Other**
Top 10 Factions (With a Top 5 balances)
Top 10 Kills
Top Balances using Holograms
Longest Lived
Play TIme

If the build could be made to suit those, more can be added as we go.

**Comment by FatedKusari** [comment]
A fair few stats stuck up, this no longer needs to be priority 2.
