### ISSUE TITLE
Fix Citizens Duplicate Gun Dealers

### ISSUE THREAD

**Issue by artfcl-intlgnce** [artfcl-intlgnce/XXMC#98]
NPC remove does not work (returns after save and reload), there is conflict in config file that needs to be manually reviewed.

**Comment by FatedKusari** [comment]
Solved with issue https://github.com/artfcl-intlgnce/NarcoWars/issues/97

There were 4 Gun Dealers muddled around, and moved around.
3 were created in the same spot (Paradise Falls) shop, 1 in (BetterSpawnWorld), being moved around so much it didnt know what to do half the time. Each reload pushed them around.
