### ISSUE TITLE
Cops

### ISSUE THREAD

**Issue by JoeS8** [artfcl-intlgnce/XXMC#99]
Been doing some brainstorming r/e cops along with feedback from players. General impression I have at the moment is that there aren't enough incentives for players to even consider applying to join the force. Current playerbase count combined with quite expensive rankup costs would make progression extremely difficult at slow at this stage - enough to put people off the idea completely. 

Corrupt Cops - this was discussed at some length between myself, Art and Hyper (not sure where he has gone). Could implement the idea or notion that cops can choose to be corrupt within the playerworld. Can do under the table deals with players to look a blind eye when they are running or even to run for them (would need discussion). Deals would have to be kept completely secret. Other police force members can apply for a fellow cop to be detained if they have enough evidence to prove corruptness, with heavy punishments such as long term imprisonment unless they get bailed out etc. 

I think this would be enough to push potential applicants over the line. Whilst there aren't as many people running, they can make big money with under the table deals. Would also add an element of unpredictability and excitement to those who enjoy it.

I think that it's important, especially now to push cops towards the public. Some people love the idea of being police but just can't see the benefits yet. If we create a platform for them to decide how they act I think the consequences will be positive.

**Comment by FatedKusari** [comment]
Just a quick thought. How about cops getting a weekly "payment".

Once a week, they are able to run a "/paycheck" command (or something along those lines", this would give them more of a reason to get another source of income. Bring some form of realism too.

**Comment by artfcl-intlgnce** [comment]
To hop off Fated's idea, I like the idea of a Salary. With our time played payouts, we can actually give certain perms to cops to get a MUCH larger 100% guaranteed payout as salary. Will implement this immediately.

**Comment by artfcl-intlgnce** [comment]
Done. Cops now get 6k/hr online (1k every 10 mins + 2 gunpowder), max 50k/day salary (plus confiscations). Automatic. Actionbar message enabled. Need community management to spread the word.

**Comment by artfcl-intlgnce** [comment]
PS.. Corruption is Okay too
